// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module region_before_dataflow_in_loop_VITIS_LOOP_65_3 (
        ap_clk,
        ap_rst,
        A,
        tilenuma,
        tilen,
        B,
        tilenumc,
        C_i,
        C_o,
        tilenuma_ap_vld,
        tilen_ap_vld,
        tilenumc_ap_vld,
        ap_start,
        A_ap_vld,
        B_ap_vld,
        C_i_ap_vld,
        C_o_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [31:0] A;
input  [31:0] tilenuma;
input  [31:0] tilen;
input  [31:0] B;
input  [31:0] tilenumc;
input  [31:0] C_i;
output  [31:0] C_o;
input   tilenuma_ap_vld;
input   tilen_ap_vld;
input   tilenumc_ap_vld;
input   ap_start;
input   A_ap_vld;
input   B_ap_vld;
input   C_i_ap_vld;
output   C_o_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [31:0] a_buf_i_q0;
wire   [31:0] a_buf_t_q0;
wire   [31:0] b_buf_i_q0;
wire   [31:0] b_buf_t_q0;
wire   [31:0] c_buf_i_q0;
wire   [31:0] c_buf_t_q0;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_full_n;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_continue;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_out;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_write;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_din;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_write;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_din;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_write;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_din;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_write;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_din;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_write;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_din;
wire    dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_write;
wire    load_a_U0_ap_start;
wire    load_a_U0_ap_done;
wire    load_a_U0_ap_continue;
wire    load_a_U0_ap_idle;
wire    load_a_U0_ap_ready;
wire   [6:0] load_a_U0_a_buf_address0;
wire    load_a_U0_a_buf_ce0;
wire    load_a_U0_a_buf_we0;
wire   [31:0] load_a_U0_a_buf_d0;
wire    load_a_U0_tilenuma_read;
wire    load_a_U0_tilen_read;
wire   [31:0] load_a_U0_tilenuma_out_din;
wire    load_a_U0_tilenuma_out_write;
wire   [31:0] load_a_U0_tilen_out_din;
wire    load_a_U0_tilen_out_write;
wire    ap_channel_done_a_buf;
wire    load_a_U0_a_buf_full_n;
wire    load_b_U0_ap_start;
wire    load_b_U0_ap_done;
wire    load_b_U0_ap_continue;
wire    load_b_U0_ap_idle;
wire    load_b_U0_ap_ready;
wire   [6:0] load_b_U0_b_buf_address0;
wire    load_b_U0_b_buf_ce0;
wire    load_b_U0_b_buf_we0;
wire   [31:0] load_b_U0_b_buf_d0;
wire    load_b_U0_tilenuma_read;
wire    load_b_U0_tilenumc_read;
wire    ap_channel_done_b_buf;
wire    load_b_U0_b_buf_full_n;
wire    conv_U0_ap_start;
wire    conv_U0_ap_done;
wire    conv_U0_ap_continue;
wire    conv_U0_ap_idle;
wire    conv_U0_ap_ready;
wire   [6:0] conv_U0_a_buf_address0;
wire    conv_U0_a_buf_ce0;
wire   [6:0] conv_U0_b_buf_address0;
wire    conv_U0_b_buf_ce0;
wire   [6:0] conv_U0_c_buf_address0;
wire    conv_U0_c_buf_ce0;
wire    conv_U0_c_buf_we0;
wire   [31:0] conv_U0_c_buf_d0;
wire    conv_U0_tilen_read;
wire    conv_U0_tilenuma_read;
wire    conv_U0_tilenumc_read;
wire   [31:0] conv_U0_tilen_out_din;
wire    conv_U0_tilen_out_write;
wire   [31:0] conv_U0_tilenumc_out_din;
wire    conv_U0_tilenumc_out_write;
wire    ap_channel_done_c_buf;
wire    conv_U0_c_buf_full_n;
wire    store_c_U0_ap_start;
wire    store_c_U0_ap_done;
wire    store_c_U0_ap_continue;
wire    store_c_U0_ap_idle;
wire    store_c_U0_ap_ready;
wire   [31:0] store_c_U0_C_o;
wire    store_c_U0_C_o_ap_vld;
wire   [6:0] store_c_U0_c_buf_address0;
wire    store_c_U0_c_buf_ce0;
wire    store_c_U0_tilenumc_read;
wire    store_c_U0_tilen_read;
wire    ap_sync_continue;
wire    a_buf_i_full_n;
wire    a_buf_t_empty_n;
wire    b_buf_i_full_n;
wire    b_buf_t_empty_n;
wire    c_buf_i_full_n;
wire    c_buf_t_empty_n;
wire    tilenuma_c_full_n;
wire   [31:0] tilenuma_c_dout;
wire    tilenuma_c_empty_n;
wire    tilenuma_c1_full_n;
wire   [31:0] tilenuma_c1_dout;
wire    tilenuma_c1_empty_n;
wire    tilen_c_full_n;
wire   [31:0] tilen_c_dout;
wire    tilen_c_empty_n;
wire    tilenumc_c_full_n;
wire   [31:0] tilenumc_c_dout;
wire    tilenumc_c_empty_n;
wire    tilenumc_c2_full_n;
wire   [31:0] tilenumc_c2_dout;
wire    tilenumc_c2_empty_n;
wire    tilenuma_c3_full_n;
wire   [31:0] tilenuma_c3_dout;
wire    tilenuma_c3_empty_n;
wire    tilen_c4_full_n;
wire   [31:0] tilen_c4_dout;
wire    tilen_c4_empty_n;
wire    tilen_c5_full_n;
wire   [31:0] tilen_c5_dout;
wire    tilen_c5_empty_n;
wire    tilenumc_c6_full_n;
wire   [31:0] tilenumc_c6_dout;
wire    tilenumc_c6_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_load_a_U0_din;
wire    start_for_load_a_U0_full_n;
wire   [0:0] start_for_load_a_U0_dout;
wire    start_for_load_a_U0_empty_n;
wire   [0:0] start_for_load_b_U0_din;
wire    start_for_load_b_U0_full_n;
wire   [0:0] start_for_load_b_U0_dout;
wire    start_for_load_b_U0_empty_n;
wire    load_a_U0_start_full_n;
wire    load_a_U0_start_write;
wire    load_b_U0_start_full_n;
wire    load_b_U0_start_write;
wire    conv_U0_start_full_n;
wire    conv_U0_start_write;
wire    store_c_U0_start_full_n;
wire    store_c_U0_start_write;

region_before_dataflow_in_loop_VITIS_LOOP_65_3_a_buf #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
a_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_a_U0_a_buf_address0),
    .i_ce0(load_a_U0_a_buf_ce0),
    .i_we0(load_a_U0_a_buf_we0),
    .i_d0(load_a_U0_a_buf_d0),
    .i_q0(a_buf_i_q0),
    .t_address0(conv_U0_a_buf_address0),
    .t_ce0(conv_U0_a_buf_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(a_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(a_buf_i_full_n),
    .i_write(load_a_U0_ap_done),
    .t_empty_n(a_buf_t_empty_n),
    .t_read(conv_U0_ap_ready)
);

region_before_dataflow_in_loop_VITIS_LOOP_65_3_a_buf #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
b_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_b_U0_b_buf_address0),
    .i_ce0(load_b_U0_b_buf_ce0),
    .i_we0(load_b_U0_b_buf_we0),
    .i_d0(load_b_U0_b_buf_d0),
    .i_q0(b_buf_i_q0),
    .t_address0(conv_U0_b_buf_address0),
    .t_ce0(conv_U0_b_buf_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(b_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(b_buf_i_full_n),
    .i_write(load_b_U0_ap_done),
    .t_empty_n(b_buf_t_empty_n),
    .t_read(conv_U0_ap_ready)
);

region_before_dataflow_in_loop_VITIS_LOOP_65_3_a_buf #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
c_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(conv_U0_c_buf_address0),
    .i_ce0(conv_U0_c_buf_ce0),
    .i_we0(conv_U0_c_buf_we0),
    .i_d0(conv_U0_c_buf_d0),
    .i_q0(c_buf_i_q0),
    .t_address0(store_c_U0_c_buf_address0),
    .t_ce0(store_c_U0_c_buf_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(c_buf_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(c_buf_i_full_n),
    .i_write(conv_U0_ap_done),
    .t_empty_n(c_buf_t_empty_n),
    .t_read(store_c_U0_ap_ready)
);

region_before_dataflow_in_loop_VITIS_LOOP_65_3_entry83 dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_start),
    .start_full_n(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_full_n),
    .ap_done(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_done),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_continue),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_idle),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_ready),
    .start_out(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_out),
    .start_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_write),
    .tilenuma(tilenuma),
    .tilen(tilen),
    .tilenumc(tilenumc),
    .tilenuma_out_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_din),
    .tilenuma_out_full_n(tilenuma_c_full_n),
    .tilenuma_out_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_write),
    .tilenuma_out1_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_din),
    .tilenuma_out1_full_n(tilenuma_c1_full_n),
    .tilenuma_out1_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_write),
    .tilen_out_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_din),
    .tilen_out_full_n(tilen_c_full_n),
    .tilen_out_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_write),
    .tilenumc_out_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_din),
    .tilenumc_out_full_n(tilenumc_c_full_n),
    .tilenumc_out_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_write),
    .tilenumc_out2_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_din),
    .tilenumc_out2_full_n(tilenumc_c2_full_n),
    .tilenumc_out2_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_write)
);

region_before_load_a load_a_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_a_U0_ap_start),
    .ap_done(load_a_U0_ap_done),
    .ap_continue(load_a_U0_ap_continue),
    .ap_idle(load_a_U0_ap_idle),
    .ap_ready(load_a_U0_ap_ready),
    .A(A),
    .a_buf_address0(load_a_U0_a_buf_address0),
    .a_buf_ce0(load_a_U0_a_buf_ce0),
    .a_buf_we0(load_a_U0_a_buf_we0),
    .a_buf_d0(load_a_U0_a_buf_d0),
    .tilenuma_dout(tilenuma_c_dout),
    .tilenuma_empty_n(tilenuma_c_empty_n),
    .tilenuma_read(load_a_U0_tilenuma_read),
    .tilen_dout(tilen_c_dout),
    .tilen_empty_n(tilen_c_empty_n),
    .tilen_read(load_a_U0_tilen_read),
    .tilenuma_out_din(load_a_U0_tilenuma_out_din),
    .tilenuma_out_full_n(tilenuma_c3_full_n),
    .tilenuma_out_write(load_a_U0_tilenuma_out_write),
    .tilen_out_din(load_a_U0_tilen_out_din),
    .tilen_out_full_n(tilen_c4_full_n),
    .tilen_out_write(load_a_U0_tilen_out_write)
);

region_before_load_b load_b_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_b_U0_ap_start),
    .ap_done(load_b_U0_ap_done),
    .ap_continue(load_b_U0_ap_continue),
    .ap_idle(load_b_U0_ap_idle),
    .ap_ready(load_b_U0_ap_ready),
    .B(B),
    .b_buf_address0(load_b_U0_b_buf_address0),
    .b_buf_ce0(load_b_U0_b_buf_ce0),
    .b_buf_we0(load_b_U0_b_buf_we0),
    .b_buf_d0(load_b_U0_b_buf_d0),
    .tilenuma_dout(tilenuma_c1_dout),
    .tilenuma_empty_n(tilenuma_c1_empty_n),
    .tilenuma_read(load_b_U0_tilenuma_read),
    .tilenumc_dout(tilenumc_c_dout),
    .tilenumc_empty_n(tilenumc_c_empty_n),
    .tilenumc_read(load_b_U0_tilenumc_read)
);

region_before_conv conv_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(conv_U0_ap_start),
    .ap_done(conv_U0_ap_done),
    .ap_continue(conv_U0_ap_continue),
    .ap_idle(conv_U0_ap_idle),
    .ap_ready(conv_U0_ap_ready),
    .a_buf_address0(conv_U0_a_buf_address0),
    .a_buf_ce0(conv_U0_a_buf_ce0),
    .a_buf_q0(a_buf_t_q0),
    .b_buf_address0(conv_U0_b_buf_address0),
    .b_buf_ce0(conv_U0_b_buf_ce0),
    .b_buf_q0(b_buf_t_q0),
    .c_buf_address0(conv_U0_c_buf_address0),
    .c_buf_ce0(conv_U0_c_buf_ce0),
    .c_buf_we0(conv_U0_c_buf_we0),
    .c_buf_d0(conv_U0_c_buf_d0),
    .tilen_dout(tilen_c4_dout),
    .tilen_empty_n(tilen_c4_empty_n),
    .tilen_read(conv_U0_tilen_read),
    .tilenuma_dout(tilenuma_c3_dout),
    .tilenuma_empty_n(tilenuma_c3_empty_n),
    .tilenuma_read(conv_U0_tilenuma_read),
    .tilenumc_dout(tilenumc_c2_dout),
    .tilenumc_empty_n(tilenumc_c2_empty_n),
    .tilenumc_read(conv_U0_tilenumc_read),
    .tilen_out_din(conv_U0_tilen_out_din),
    .tilen_out_full_n(tilen_c5_full_n),
    .tilen_out_write(conv_U0_tilen_out_write),
    .tilenumc_out_din(conv_U0_tilenumc_out_din),
    .tilenumc_out_full_n(tilenumc_c6_full_n),
    .tilenumc_out_write(conv_U0_tilenumc_out_write)
);

region_before_store_c store_c_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(store_c_U0_ap_start),
    .ap_done(store_c_U0_ap_done),
    .ap_continue(store_c_U0_ap_continue),
    .ap_idle(store_c_U0_ap_idle),
    .ap_ready(store_c_U0_ap_ready),
    .C_i(C_i),
    .C_o(store_c_U0_C_o),
    .C_o_ap_vld(store_c_U0_C_o_ap_vld),
    .c_buf_address0(store_c_U0_c_buf_address0),
    .c_buf_ce0(store_c_U0_c_buf_ce0),
    .c_buf_q0(c_buf_t_q0),
    .tilenumc_dout(tilenumc_c6_dout),
    .tilenumc_empty_n(tilenumc_c6_empty_n),
    .tilenumc_read(store_c_U0_tilenumc_read),
    .tilen_dout(tilen_c5_dout),
    .tilen_empty_n(tilen_c5_empty_n),
    .tilen_read(store_c_U0_tilen_read)
);

region_before_fifo_w32_d2_S tilenuma_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_din),
    .if_full_n(tilenuma_c_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out_write),
    .if_dout(tilenuma_c_dout),
    .if_empty_n(tilenuma_c_empty_n),
    .if_read(load_a_U0_tilenuma_read)
);

region_before_fifo_w32_d2_S tilenuma_c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_din),
    .if_full_n(tilenuma_c1_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenuma_out1_write),
    .if_dout(tilenuma_c1_dout),
    .if_empty_n(tilenuma_c1_empty_n),
    .if_read(load_b_U0_tilenuma_read)
);

region_before_fifo_w32_d2_S tilen_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_din),
    .if_full_n(tilen_c_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilen_out_write),
    .if_dout(tilen_c_dout),
    .if_empty_n(tilen_c_empty_n),
    .if_read(load_a_U0_tilen_read)
);

region_before_fifo_w32_d2_S tilenumc_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_din),
    .if_full_n(tilenumc_c_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out_write),
    .if_dout(tilenumc_c_dout),
    .if_empty_n(tilenumc_c_empty_n),
    .if_read(load_b_U0_tilenumc_read)
);

region_before_fifo_w32_d3_S tilenumc_c2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_din),
    .if_full_n(tilenumc_c2_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_tilenumc_out2_write),
    .if_dout(tilenumc_c2_dout),
    .if_empty_n(tilenumc_c2_empty_n),
    .if_read(conv_U0_tilenumc_read)
);

region_before_fifo_w32_d2_S tilenuma_c3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_a_U0_tilenuma_out_din),
    .if_full_n(tilenuma_c3_full_n),
    .if_write(load_a_U0_tilenuma_out_write),
    .if_dout(tilenuma_c3_dout),
    .if_empty_n(tilenuma_c3_empty_n),
    .if_read(conv_U0_tilenuma_read)
);

region_before_fifo_w32_d2_S tilen_c4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_a_U0_tilen_out_din),
    .if_full_n(tilen_c4_full_n),
    .if_write(load_a_U0_tilen_out_write),
    .if_dout(tilen_c4_dout),
    .if_empty_n(tilen_c4_empty_n),
    .if_read(conv_U0_tilen_read)
);

region_before_fifo_w32_d2_S tilen_c5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_U0_tilen_out_din),
    .if_full_n(tilen_c5_full_n),
    .if_write(conv_U0_tilen_out_write),
    .if_dout(tilen_c5_dout),
    .if_empty_n(tilen_c5_empty_n),
    .if_read(store_c_U0_tilen_read)
);

region_before_fifo_w32_d2_S tilenumc_c6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_U0_tilenumc_out_din),
    .if_full_n(tilenumc_c6_full_n),
    .if_write(conv_U0_tilenumc_out_write),
    .if_dout(tilenumc_c6_dout),
    .if_empty_n(tilenumc_c6_empty_n),
    .if_read(store_c_U0_tilenumc_read)
);

region_before_start_for_load_a_U0 start_for_load_a_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_load_a_U0_din),
    .if_full_n(start_for_load_a_U0_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_write),
    .if_dout(start_for_load_a_U0_dout),
    .if_empty_n(start_for_load_a_U0_empty_n),
    .if_read(load_a_U0_ap_ready)
);

region_before_start_for_load_b_U0 start_for_load_b_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_load_b_U0_din),
    .if_full_n(start_for_load_b_U0_full_n),
    .if_write(dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_write),
    .if_dout(start_for_load_b_U0_dout),
    .if_empty_n(start_for_load_b_U0_empty_n),
    .if_read(load_b_U0_ap_ready)
);

assign C_o = store_c_U0_C_o;

assign C_o_ap_vld = store_c_U0_C_o_ap_vld;

assign ap_channel_done_a_buf = load_a_U0_ap_done;

assign ap_channel_done_b_buf = load_b_U0_ap_done;

assign ap_channel_done_c_buf = conv_U0_ap_done;

assign ap_done = store_c_U0_ap_done;

assign ap_idle = (store_c_U0_ap_idle & load_b_U0_ap_idle & load_a_U0_ap_idle & (c_buf_t_empty_n ^ 1'b1) & (1'b1 ^ a_buf_t_empty_n) & (b_buf_t_empty_n ^ 1'b1) & dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_idle & conv_U0_ap_idle);

assign ap_ready = dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = store_c_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_ready;

assign conv_U0_ap_continue = c_buf_i_full_n;

assign conv_U0_ap_start = (b_buf_t_empty_n & a_buf_t_empty_n);

assign conv_U0_c_buf_full_n = c_buf_i_full_n;

assign conv_U0_start_full_n = 1'b1;

assign conv_U0_start_write = 1'b0;

assign dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_continue = 1'b1;

assign dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_ap_start = ap_start;

assign dataflow_in_loop_VITIS_LOOP_65_3_entry83_U0_start_full_n = (start_for_load_b_U0_full_n & start_for_load_a_U0_full_n);

assign load_a_U0_a_buf_full_n = a_buf_i_full_n;

assign load_a_U0_ap_continue = a_buf_i_full_n;

assign load_a_U0_ap_start = start_for_load_a_U0_empty_n;

assign load_a_U0_start_full_n = 1'b1;

assign load_a_U0_start_write = 1'b0;

assign load_b_U0_ap_continue = b_buf_i_full_n;

assign load_b_U0_ap_start = start_for_load_b_U0_empty_n;

assign load_b_U0_b_buf_full_n = b_buf_i_full_n;

assign load_b_U0_start_full_n = 1'b1;

assign load_b_U0_start_write = 1'b0;

assign start_for_load_a_U0_din = 1'b1;

assign start_for_load_b_U0_din = 1'b1;

assign store_c_U0_ap_continue = ap_continue;

assign store_c_U0_ap_start = c_buf_t_empty_n;

assign store_c_U0_start_full_n = 1'b1;

assign store_c_U0_start_write = 1'b0;

endmodule //region_before_dataflow_in_loop_VITIS_LOOP_65_3
